[package]
name = "Rust-Mnemonic-Generator"
version = "1.0.0"
edition = "2024"

[dependencies]
rand = "0.8"
sha2 = "0.10"
sha3 = "0.10"
hmac ={ version = "0.12.1", features = ["std"] }
bitcoin = "0.32.5"
secp256k1 = "0.30.0"
pbkdf2 = "0.12.2"
hex = "0.4.3"