name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: rustup component add clippy rustfmt

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose

    - name: Lint Code
      run: cargo clippy -- -D warnings

    - name: Check Code Formatting
      run: cargo fmt -- --check
